### PR TITLE
request KeePass entry on shortcut only, based on PR #484

### PR DESCRIPTION
**Pull request by fersingb**
Hi, based on @drauch's work, I added the missing changes to the background/page.js file. It's a quick edit, I'm not sure if I'm missing something. Let me know if it's wrong.

Thanks

### CODE REVIEW

**Comment by fersingb** [comment]
Hi,

The PR has been there for a month now. Will it be merged in master for the next release?  @pfn ? When is the next release planned?

Thanks

**Comment by pfn** [comment]
I have been in the hospital for the past month. I will see about reviewing
this in the next couple weeks.

**Comment by fersingb** [comment]
Oh ok, I understand. No rush.

**Comment by drauch** [comment]
Nice, looking forward to a release. Thank you @fersingb  & @pfn !

**Pull request merged**
