### PR TITLE
Block specific pages

### PR DESCRIPTION
**Pull request by chrahunt**
This is unfinished, but I think now is the appropriate time to get feedback. This applies solely to chromeIPass.

This partially addresses #258 and addresses #267 and #171, which are all concerned with excluding actions on specific pages. My implementation adds a section to the chromeIPass options page that allows users to add URLs/patterns that are matched to the full URL of the page being viewed. Two methods of matching are supported:
- Regular expressions
- A simpler syntax that uses \* as a wildcard

If this solution seems to be on the right track w.r.t. the issues mentioned above; there were a few other items I intended to address:
- Right now this essentially removes the ability for chromeIPass to interact with a matched page, but I would like to extend this to prevent KeePass queries on activation of the tab holding the blocked page as well, which would prevent the KeePass password request dialog and fully address #258.
- ~~Syntax error handling and general input validation when a new pattern is being added.~~ Added.
- Allowing addition of pages via browser action popup. Pressing a button in the browser action popup would bring up a dialog box that would allow editing and addition of a pattern (which would be initially populated with the current page's full URL).
- Browser action icon and popup reflecting the current page's block status.
- ~~Temporary suspension of block status. If the user wishes to temporarily suspend the block on the current page they need only press a button on the browser action popup to do so. This is already possible and can be demonstrated on a blocked page via the console.~~ A prototype of this has been implemented. A button on the browser action popup window on blocked pages allows for suspension of the blocking, and will replay all the normal actions that chromeIPass takes on the page that were blocked without requiring a refresh. The style of the blocked page indicator could use work.
- See pattern that is resulting in a page being blocked. Clicking a button on the browser action popup would bring the user to the options page with the 'Block Pages' tab selected and highlight the row with the rule that matches the current page.
- ~~Better handling for pages with iframes. Currently the content script is invoked once on page load for the parent page and at least once if there is an iframe (in the context of that iframe); I have not tested the number of pages. This 'double-invocation' causes an issue because the `document.href` attribute is the location of the iframe, which may not match the pattern intended to prevent action on the current page.~~ This has been resolved.

Additionally, this lays the framework for a solution to #245 and #271. At least, the same concept of matching the URLs could be used to specify pages on which to block autofill (but still allow for action when the credential input field is selected).

### CODE REVIEW

**Comment by chrahunt** [comment]
This has been updated. There is still some functionality left to be implemented, as outlined in my first comment. Any indicator that what I have so far is acceptable and I'm clear to proceed would be great.

**Comment by cschneidr** [comment]
No feedback here? I, at least, would appreciate the feature :+1:

**Comment by pfn** [comment]
Oh, this has been sitting for a while huh... damn, thought I reviewed it a long time ago, I'll see if I can scrounge some time to look at it soon.

**Comment by cschneidr** [comment]
Great! *fingers crossed*

**Comment by chrahunt** [comment]
Let me know if I need to change anything on this; in hindsight I don't think the "unblock page without requiring reload" use case is worth queuing the jQuery DOM edit calls.

**Comment by pfn** [comment]
alright, lets rebase on latest since I merged a bunch of PRs and this no longer merges cleanly, and it'll go in.

Thanks

**Comment by chrahunt** [comment]
I don't have time to work on this (and I now just use the built-in KeePass autotype), but anyone can feel free to pick this up where I left it.

**Pull request closed without merging**
